// Projects and case studies shown in /projects and featured on the home page.
// Tip: keep "category" values consistent – they power the category filters.

// Import all project images so Vite bundles them (required for GitHub Pages)
const projectImages = import.meta.glob('../assets/*.png', { eager: true, query: '?url', import: 'default' })
const getImage = (filename) => projectImages[`../assets/${filename}`] || `../assets/${filename}`

export const projects = [
  {
    index: 1,
    title: 'Low-Light Enhancement (GAN vs U-Net)',
    subtitle: 'Computer Vision · Deep Learning',
    summary:
      'Deep-learning low-light image enhancement comparing GAN and U-Net architectures. Focused on visibility recovery, contrast improvement, and noise suppression under extreme lighting.',
    tags: ['TensorFlow', 'Keras', 'GAN', 'U-Net', 'Image Processing'],
    focus: 'Enhancement quality vs structural preservation in low-light scenes.',
    link: 'https://github.com/El7agAdel/Low-Light-Enhancement-GAN-vs-UNet',
    category: 'Computer Vision',
    featured: true,
    year: 2025,
    image: getImage('LLE.png'),
  },
  {
    index: 2,
    title: 'Valorant Overlay HUD',
    subtitle: 'Broadcast · Real-time CV + Graphics',
    summary:
      'A real-time Valorant HUD using Unreal Engine + HTML overlays, powered by computer vision and OCR to extract live in-game state and render broadcast graphics.',
    tags: ['OpenCV', 'OCR', 'Python', 'Unreal Engine', 'HTML/CSS/JS'],
    focus: 'Low-latency extraction + production-grade rendering and reliability.',
    link: 'https://www.youtube.com/watch?v=ZxQeYySgf-8&t=10420s',
    category: 'Computer Vision',
    featured: true,
    year: 2025,
    image: getImage('Valo.png'),

  },
  {
    index: 3,
    title: 'League of Legends Overlay HUD',
    subtitle: 'Broadcast · Real-time CV + Graphics',
    summary:
      'A real-time League Of Legends HUD using Unreal Engine + HTML overlays, powered by computer vision and OCR to extract live in-game state and render broadcast graphics.',
    tags: ['OpenCV', 'OCR', 'Python', 'Unreal Engine', 'HTML/CSS/JS'],
    focus: 'UI-state reconstruction and robust detection under broadcast constraints.',
    link: 'https://www.youtube.com/watch?v=3bvnZs5T8GU&t=7451s',
    category: 'Computer Vision',
    featured: true,
    year: 2025,
    image: getImage('LOL.png'),
  },
  {
    index: 4,
    title: 'KAYO – Marker-based Tracking',
    subtitle: 'Augmented Reality · Tracking',
    summary:
      'Marker-based tracking prototype for AR-style positioning. Built with classical vision techniques to detect and track a fiducial marker and recover pose-like signals.',
    tags: ['OpenCV', 'Tracking', 'Pose Estimation', 'Image Processing'],
    focus: 'Stable tracking and jitter reduction in real-time camera feeds.',
    link: 'https://youtu.be/Fqq4itgHDtM',
    category: 'Augmented Reality',
    featured: false,
    year: 2025,
    image: getImage('kayo.png'),
  },
  {
    index: 4,
    title: 'Virtual Restaurant',
    subtitle: 'Augmented Reality · Mobile AR',
    summary:
      'Web AR solution for fine dining immersive experience',
    tags: ['WebAR', 'Tracking', 'Immersive Experience'],
    focus: 'Stable tracking and jitter reduction in real-time camera feeds.',
    link: 'https://youtu.be/YfkPUAzF6PI',
    category: 'Augmented Reality',
    featured: false,
    year: 2026,
    image: getImage('Virtual_Restaurant.png'),
  },
  {
    index: 4,
    title: 'PUGB AR',
    subtitle: 'Augmented Reality · Mobile AR',
    summary:
      'Promotional Campaign for New Sanhok Destruction Release',
    tags: ['OpenCV', 'Tracking', 'Pose Estimation', 'Image Processing'],
    focus: 'Stable tracking and jitter reduction in real-time camera feeds.',
    // link: 'https://youtu.be/Fqq4itgHDtM',
    category: 'Augmented Reality',
    featured: false,
    year: 2024,
    image: getImage('arpubg.png'),
  },
  {
    index: 5,
    title: 'Meta-HUMAN',
    subtitle: 'Augmented Reality · Tracking',
    summary:
      'Marker-based tracking prototype for AR-style positioning. Integrated with realtime Face-Mesh Tracking , and realtime voice augmentation',
    tags: ['OpenCV', 'Tracking', 'Pose Estimation', 'Image Processing', 'Face Tracking', 'Voice Augmentation'],
    focus: 'Multi-Functional realtime  virtual production systems.',
    link: 'https://youtu.be/735IsHcaQYc',
    category: 'Augmented Reality',
    featured: false,
    year: 2025,
    image: getImage('metahuman.png'),
  },
  {
    index: 6,
    title: 'ORBSLAM-AR',
    subtitle: 'Augmented Reality · Tracking',
    summary:
      'Integrating state-of-the-art ORBSLAM with Unreal Engine utilizing pose estimation and mapping techniques to render a 3D model',
    tags: ['SLAM', 'Unreal', 'Pose Estimation'],
    focus: 'Stable tracking and jitter reduction in real-time camera feeds.',
    link: 'https://youtu.be/iYZwIN7IkSE',
    category: 'Augmented Reality',
    featured: false,
    year: 2025,
    image: getImage('arorb.png'),
  },
  {
    index: 7,
    title: 'Tetris – HandPlay',
    subtitle: 'Computer Vision · Human Interaction',
    summary:
      'Hand-gesture controlled Tetris using MediaPipe hand landmarks as an input device for a simple game loop.',
    tags: ['MediaPipe', 'Python', 'Computer Vision'],
    focus: 'Robust gesture mapping and responsive control.',
    link: '#',
    category: 'Computer Vision',
    featured: false,
    year: 2026,
    image: getImage('tetris.png'),
  },

  // --- Broadcast / event case studies (rename + fill details) ---
  {
    index: 8,
    title: 'Grand Egyption Museum',
    subtitle: 'Broadcast · Audio / Comms',
    summary:
      'Part of the Audio Engineering team responsible for routing and maintaing audio signals to various pin-points in the venue',
    tags: ['Broadcast', 'Audio', 'Comms', 'Operations'],
    focus: 'Stable show delivery under real-time constraints.',
    // link: 'https://www.linkedin.com/posts/arabhardware.net_iac2022-iac2022-BroadCast-activity-7005652485398794241-5ibR/',
    category: 'BroadCast',
    featured: false,
    year: 2025,
    image: getImage('museum.png'),
  },
  {
    index: 9,
    title: 'IAC 2022',
    subtitle: 'Broadcast · Audio / Video / Comms',
    summary:
      'Live event delivery as part of the broadcast engineering team (roles included audio, video, comms, and systems reliability).',
    tags: ['Broadcast', 'Audio', 'Video', 'Comms', 'Operations'],
    focus: 'Stable show delivery under real-time constraints.',
    link: 'https://www.linkedin.com/posts/arabhardware%2Enet_iac2022-iac2022-esports-activity-7005652485398794241-5ibR?utm_source=share&utm_medium=member_desktop&rcm=ACoAABypsIABjuzVBRV-vEBoMb1QzFhxjlWjnsY',
    category: 'BroadCast',
    featured: false,
    year: 2022,
    image: getImage('iac.png'),
  },
  {
    index: 10,
    title: 'ESS',
    subtitle: 'Broadcast · Engineering & Operations',
    summary:
      'Delivered live production engineering (signal flow, routing, troubleshooting, and on-site operations).',
    tags: ['Broadcast', 'Signal Flow', 'Routing', 'On-site Ops'],
    focus: 'Stable show delivery under real-time constraints.',
    link: 'https://www.linkedin.com/posts/ahmed-abdel-latif-03398036_and-its-a-wrap-on-ess25-as-esports-summit-activity-7384135951733735424-rJdf?utm_source=share&utm_medium=member_desktop&rcm=ACoAABypsIABjuzVBRV-vEBoMb1QzFhxjlWjnsY',
    category: 'BroadCast',
    featured: false,
    year: 2025,
    image: getImage('summit.png'),
  },
  {
    index: 11,
    title: 'Proseed',
    subtitle: 'Broadcast · Audio / Video / Comms',
    summary:
      'Multi-role support across audio/video/comms and show control for a live event environment.',
    tags: ['Broadcast', 'Audio', 'Video', 'Comms'],
    focus: 'Stable show delivery under real-time constraints.',
    link: 'https://www.linkedin.com/posts/hashemalborno_esports-gamingindustry-activity-7114504284402036738-1WJB?utm_source=share&utm_medium=member_desktop&rcm=ACoAABypsIABjuzVBRV-vEBoMb1QzFhxjlWjnsY',
    image: getImage('Proseed.png'),
    category: 'BroadCast',
    featured: false,
    year: 2023,
  },
  {
    index: 12,
    title: 'Campus Clutch',
    subtitle: 'Broadcast · Audio / Video / Comms',
    summary:
      'Multi-role support across audio/video/comms and show control for a live event environment.',
    tags: ['Broadcast', 'Audio', 'Video', 'Comms'],
    focus: 'Stable show delivery under real-time constraints.',
    link: 'https://www.linkedin.com/posts/hashemalborno_esports-gamerslounge-gaming-activity-6995698318609661953-UVu1?utm_source=share&utm_medium=member_desktop&rcm=ACoAABypsIABjuzVBRV-vEBoMb1QzFhxjlWjnsY',
    category: 'BroadCast',
    featured: false,
    year: 2022,
    image: getImage('campus.png'),
  },
  {
    index: 13,
    title: 'Red Bull Arcade',
    subtitle: 'Embedded · Interactive Systems',
    summary:
      'Interactive experience build-out (hardware + software) for a live activation setup.',
    tags: ['Embedded', 'Computer Vision', 'Interactive'],
    focus: 'End-to-end delivery across hardware + software.',
    link: 'https://www.linkedin.com/posts/ahmed-abdel-latif-03398036_esports-gaming-redbull-activity-7305195848525647872-htOv/?utm_source=share&utm_medium=member_desktop&rcm=ACoAABypsIABjuzVBRV-vEBoMb1QzFhxjlWjnsY',
    category: 'Embedded Systems',
    featured: false,
    year: 2024,
    image: getImage('arcade.png'),
  },
  {
    index: 14,
    title: 'ROS_BCI',
    subtitle: 'Embedded · Interactive Systems',
    summary:
      'Interactive experience build-out (hardware + software) for a live activation setup. (Details available on request.)',
    tags: ['Embedded', 'Computer Vision', 'Interactive'],
    focus: 'End-to-end delivery across hardware + software.',
    link: 'https://www.youtube.com/watch?v=5liWwQx0vOA',
    category: 'Robotics',
    featured: false,
    year: 2020,
    image: getImage('bci.png'),
  },
  {
    index: 15,
    title: 'ABB Reinforcement Learning',
    subtitle: 'Embedded · Interactive Systems',
    summary:
      'Interactive experience build-out (hardware + software) for a live activation setup. (Details available on request.)',
    tags: ['Embedded', 'Computer Vision', 'Interactive'],
    focus: 'End-to-end delivery across hardware + software.',
    link: 'https://github.com/El7agAdel/ABB_IRB120_Reinforcement_Learning?tab=readme-ov-file',
    category: 'Robotics',
    featured: false,
    year: 2020,
    image: getImage('abbrl.png'),
  },
  {
    index: 16,
    title: 'Catalyst CRS ROS2 Humble',
    subtitle: 'Embedded · Interactive Systems',
    summary:
      'Interactive experience build-out (hardware + software) for a live activation setup. (Details available on request.)',
    tags: ['Embedded', 'Computer Vision', 'Interactive'],
    focus: 'End-to-end delivery across hardware + software.',
    link: 'https://github.com/El7agAdel/Catalyst-CRS-ROS-Humble',
    category: 'Robotics',
    featured: false,
    year: 2026,
    image: getImage('catalystros2.png'),
  },
  {
    index: 17,
    title: 'Abb IRB120 ROS2 Humble',
    subtitle: 'Embedded · Interactive Systems',
    summary:
      'Interactive experience build-out (hardware + software) for a live activation setup. (Details available on request.)',
    tags: ['Embedded', 'Computer Vision', 'Interactive'],
    focus: 'End-to-end delivery across hardware + software.',
    link: 'https://github.com/El7agAdel/Abb-IRB120-ROS-Humble',
    category: 'Robotics',
    featured: false,
    year: 2026,
    image: getImage('abbros2.png'),
  },
  // // --- Placeholders for what you told me you focus on (fill when ready) ---
  // {
  //   title: 'SLAM / Robotics Research (Masters)',
  //   subtitle: 'SLAM · Robotics · Research',
  //   summary:
  //     'Ongoing research work during M.Sc. (add your thesis topic, datasets, and any public artifacts).',
  //   tags: ['SLAM', 'Robotics', 'Sensor Fusion'],
  //   focus: 'Tracking robustness and map consistency under real-world sensor noise.',
  //   link: '#',
  //   category: 'SLAM & Robotics',
  //   featured: false,
  //   year: 2026,
  //   draft: true,
  // },
]
